[package]
name = "FirstBevyGame"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] }

# for my sanity
# [profile.dev.package."*"]
# opt-level = 3
